---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-global-objects-crb
subjects:
  - kind: ServiceAccount
    name: k8s-global-objects
    namespace: k8s-global-objects
roleRef:
  kind: ClusterRole
  name: k8s-global-objects-cr
  apiGroup: rbac.authorization.k8s.io
